/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 04:30:40 GMT 2017
 */

package simhash;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.TooManyResourcesException;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import simhash.Main;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Main_ESTest extends Main_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[5];
      Main.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[2];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/home/rewt/Documents/CS362-001-SP17/projects/jensejac/assignment-1/m?{zw^{rER@G{");
      byte[] byteArray0 = new byte[9];
      byteArray0[0] = (byte) (-60);
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      stringArray0[0] = "m?{zw^{rER@G{";
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "&P(*f#~?O7)k9'04<?n";
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/home/rewt/Documents/CS362-001-SP17/projects/jensejac/assignment-1/&P(*f#~?O7)k9'04<?n");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "$V=H");
      FileSystemHandling.shouldAllThrowIOExceptions();
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         assertThrownBy("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "oE#";
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "&P(*f#~?O7)k9'04<?n";
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/home/rewt/Documents/CS362-001-SP17/projects/jensejac/assignment-1/&P(*f#~?O7)k9'04<?n");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "&P(*f#~?O7)k9'04<?n");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "]");
      stringArray0[1] = "c{_";
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "&P(*f#~?O7)k9'04<?n");
      Main.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "&P(*f#~?O7)k9'04<?n";
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/home/rewt/Documents/CS362-001-SP17/projects/jensejac/assignment-1/&P(*f#~?O7)k9'04<?n");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "&P(*f#~?O7)k9'04<?n");
      stringArray0[1] = "P{|";
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "&P(*f#~?O7)k9'04<?n");
      Main.main(stringArray0);
      Main.main(stringArray0);
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "&P(*f#~?O7)k9'04<?n";
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/home/rewt/Documents/CS362-001-SP17/projects/jensejac/assignment-1/&P(*f#~?O7)k9'04<?n");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "]");
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[1];
      Main.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Main main0 = new Main();
  }
}
