/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 04:32:03 GMT 2017
 */

package simhash;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteBuffer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import simhash.MurmurHash;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MurmurHash_ESTest extends MurmurHash_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      long long0 = MurmurHash.hash64((ByteBuffer) null, 0, 0, 150L);
      assertEquals(7240152504610985402L, long0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      long long0 = MurmurHash.hash64((ByteBuffer) null, 0, 0, (-104L));
      assertEquals((-6274123720903079261L), long0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = MurmurHash.hash32((ByteBuffer) null, 0, (-516), 106);
      assertEquals(4454554, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int int0 = MurmurHash.hash32((ByteBuffer) null, 2757, 0, 8);
      assertEquals((-561057354), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int int0 = MurmurHash.hash32("~.");
      assertEquals((-1125664738), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash64((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash32((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash64((ByteBuffer) null, 0, (-1519), (long) (-1519));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      long long0 = MurmurHash.hash64((ByteBuffer) null, 1965, 0, (long) 0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash64((ByteBuffer) null, (-485), (-485), (long) (-485));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash64((ByteBuffer) null, 224, 224, (long) 224);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash32((ByteBuffer) null, (-73), (-73), 3283);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      int int0 = MurmurHash.hash32((ByteBuffer) null, 2757, 0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash32((ByteBuffer) null, 1403, 2757, 2757);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash64((ByteBuffer) null, (-1), (-1), (long) (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash64((ByteBuffer) null, (-1125664738), (-1125664738), 4559921381184026945L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash64((ByteBuffer) null, (-251), (-251), (long) (-251));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash64((ByteBuffer) null, 0, (-44), (long) (-44));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash64((ByteBuffer) null, (-3726), (-3726), (long) (-3726));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      long long0 = MurmurHash.hash64("Y");
      assertEquals(4918752717281726814L, long0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      long long0 = MurmurHash.hash64("");
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash64("BAgyXIbcWk#MY BD%bs");
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // 19
         //
         assertThrownBy("java.nio.HeapByteBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash32((ByteBuffer) null, (-1223), (-1223), (-1223));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      // Undeclared exception!
      try { 
        MurmurHash.hash32((ByteBuffer) null, 4361, (-78), (-78));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.MurmurHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      int int0 = MurmurHash.hash32("BAgyXIbcWk#MY BD%bs");
      assertEquals(540993210, int0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      int int0 = MurmurHash.hash32("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MurmurHash murmurHash0 = new MurmurHash();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      long long0 = MurmurHash.hash64("g|G");
      assertEquals((-1894749367489591620L), long0);
  }
}
