/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 04:33:27 GMT 2017
 */

package simhash;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import simhash.BinaryWordSeg;
import simhash.IWordSeg;
import simhash.Simhash;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Simhash_ESTest extends Simhash_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BinaryWordSeg binaryWordSeg0 = new BinaryWordSeg();
      Simhash simhash0 = new Simhash((IWordSeg) binaryWordSeg0);
      simhash0.simhash32("KGd/CI=w[Ue");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BinaryWordSeg binaryWordSeg0 = new BinaryWordSeg();
      Simhash simhash0 = new Simhash((IWordSeg) binaryWordSeg0);
      simhash0.hammingDistance(0L, 0L);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BinaryWordSeg binaryWordSeg0 = new BinaryWordSeg();
      Simhash simhash0 = new Simhash((IWordSeg) binaryWordSeg0);
      simhash0.hammingDistance((-2500), 1998);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BinaryWordSeg binaryWordSeg0 = new BinaryWordSeg();
      Simhash simhash0 = new Simhash((IWordSeg) binaryWordSeg0);
      // Undeclared exception!
      try { 
        simhash0.simhash64((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.BinaryWordSeg", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BinaryWordSeg binaryWordSeg0 = new BinaryWordSeg();
      Simhash simhash0 = new Simhash((IWordSeg) binaryWordSeg0);
      // Undeclared exception!
      try { 
        simhash0.simhash32((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("simhash.BinaryWordSeg", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BinaryWordSeg binaryWordSeg0 = new BinaryWordSeg();
      Simhash simhash0 = new Simhash((IWordSeg) binaryWordSeg0);
      simhash0.simhash32("Z?FnbaXC-YC+p_4M");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BinaryWordSeg binaryWordSeg0 = new BinaryWordSeg();
      Simhash simhash0 = new Simhash((IWordSeg) binaryWordSeg0);
      simhash0.simhash32("");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BinaryWordSeg binaryWordSeg0 = new BinaryWordSeg();
      Simhash simhash0 = new Simhash((IWordSeg) binaryWordSeg0);
      long long0 = simhash0.simhash64("Z?FnbaXC-YC+p_4M");
      assertEquals(2702872278030667848L, long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BinaryWordSeg binaryWordSeg0 = new BinaryWordSeg();
      Simhash simhash0 = new Simhash((IWordSeg) binaryWordSeg0);
      long long0 = simhash0.simhash64("W");
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BinaryWordSeg binaryWordSeg0 = new BinaryWordSeg();
      Simhash simhash0 = new Simhash((IWordSeg) binaryWordSeg0);
      int int0 = simhash0.hammingDistance(3689348814741910323L, (-1L));
      assertEquals(32, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BinaryWordSeg binaryWordSeg0 = new BinaryWordSeg();
      Simhash simhash0 = new Simhash((IWordSeg) binaryWordSeg0);
      int int0 = simhash0.hammingDistance(0, 0);
      assertEquals(0, int0);
  }
}
